stages:
  - test
  - build

before_script:
  - sudo apt-get update
  - sudo apt-get install curl -y
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y

raspbian_test:
  stage: test
  tags:
    - raspberrypi
    - raspbian
    - arm
  image: raspbian/stretch
  script:
    - cargo test --verbose

raspbian_build:
  stage: build
  tags:
    - raspberrypi
    - raspbian
    - arm
  image: raspbian/stretch
  script:
    - cargo build --release --verbose