stages:
  - test
  - lint
  - build

before_script:
  - apt-get update -qq
  - apt-get -y install curl -qq
  - apt-get -y install build-essential -qq
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
  - source ~/.cargo/env

raspbian_test:
  stage: test
  tags:
    - raspberrypi
    - raspbian
    - armv7
  script:
    - cargo test --verbose

raspbian_lint:
  stage: lint
  tags:
    - raspbian
  script:
    - rustup component add clippy
    - cargo install clippy -v
  allow_failure: true

raspbian_build:
  stage: build
  tags:
    - raspberrypi
    - raspbian
    - armv7
  script:
    - cargo build --release --verbose
